// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.mchnai;

@kotlin.jvm.JvmName("-initializenumMessages")
public inline fun numMessages(block: com.example.mchnai.NumMessagesKt.Dsl.() -> kotlin.Unit): com.example.mchnai.Service.NumMessages =
  com.example.mchnai.NumMessagesKt.Dsl._create(com.example.mchnai.Service.NumMessages.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `NumMessages`
 */
public object NumMessagesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.mchnai.Service.NumMessages.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.mchnai.Service.NumMessages.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.mchnai.Service.NumMessages = _builder.build()

    /**
     * `int32 count = 1;`
     */
    public var count: kotlin.Int
      @JvmName("getCount")
      get() = _builder.count
      @JvmName("setCount")
      set(value) {
        _builder.count = value
      }
    /**
     * `int32 count = 1;`
     */
    public fun clearCount() {
      _builder.clearCount()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.mchnai.Service.NumMessages.copy(block: `com.example.mchnai`.NumMessagesKt.Dsl.() -> kotlin.Unit): com.example.mchnai.Service.NumMessages =
  `com.example.mchnai`.NumMessagesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

