// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.mchnai;

@kotlin.jvm.JvmName("-initializestringMessage")
public inline fun stringMessage(block: com.example.mchnai.StringMessageKt.Dsl.() -> kotlin.Unit): com.example.mchnai.Service.StringMessage =
  com.example.mchnai.StringMessageKt.Dsl._create(com.example.mchnai.Service.StringMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `StringMessage`
 */
public object StringMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.mchnai.Service.StringMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.mchnai.Service.StringMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.mchnai.Service.StringMessage = _builder.build()

    /**
     * `string message = 1;`
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.message
      @JvmName("setMessage")
      set(value) {
        _builder.message = value
      }
    /**
     * `string message = 1;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.mchnai.Service.StringMessage.copy(block: `com.example.mchnai`.StringMessageKt.Dsl.() -> kotlin.Unit): com.example.mchnai.Service.StringMessage =
  `com.example.mchnai`.StringMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

